[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/library"
  to = "/library.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/reader"
  to = "/reader.html"
  status = 200
